// <auto-generated />
using System;
using DAL;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DAL.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20200313100736_updatenew")]
    partial class updatenew
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.8-servicing-32085")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BO.Models.RoleEntity", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Role");
                });

            modelBuilder.Entity("BO.Models.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("AssignedTo");

                    b.Property<string>("CreatedBy");

                    b.Property<string>("Description");

                    b.Property<DateTime?>("EndTime");

                    b.Property<bool>("IsAccepted");

                    b.Property<bool>("IsApproved");

                    b.Property<bool>("IsDone");

                    b.Property<double?>("Mark");

                    b.Property<string>("Name");

                    b.Property<string>("Note");

                    b.Property<DateTime?>("NoteTime");

                    b.Property<string>("Reason");

                    b.Property<DateTime>("StartTime");

                    b.Property<int>("Status");

                    b.Property<DateTime?>("UpdateTime");

                    b.Property<string>("Updateby");

                    b.HasKey("Id");

                    b.HasIndex("AssignedTo");

                    b.ToTable("Task");
                });

            modelBuilder.Entity("BO.Models.UserEntity", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<int>("GroupId");

                    b.Property<string>("Password");

                    b.Property<int>("RoleId");

                    b.Property<DateTime>("UpdateTime");

                    b.Property<string>("UpdatedBy");

                    b.Property<string>("UserName");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.HasIndex("RoleId");

                    b.ToTable("User");
                });

            modelBuilder.Entity("BO.Models.UserManage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ManagedBy");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("UserManage");
                });

            modelBuilder.Entity("BO.Models.TaskEntity", b =>
                {
                    b.HasOne("BO.Models.UserEntity", "User")
                        .WithMany("Task")
                        .HasForeignKey("AssignedTo");
                });

            modelBuilder.Entity("BO.Models.UserEntity", b =>
                {
                    b.HasOne("BO.Models.UserManage", "UserManages")
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("BO.Models.RoleEntity", "RoleEntity")
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade);
                });
#pragma warning restore 612, 618
        }
    }
}
